{
 "title": "Spam Detection Text Embedding Drift",
 "time": { "from": "2024-07-26T14:31:15.696Z", "to": "2024-07-26T14:33:28.411Z" },
 "panels": [
  {
   "title": "Model Type Embedding Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT model_drift, \"timestamp\" FROM embedding_drift_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "MMD Type Embedding Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT mmd_drift, \"timestamp\" FROM embedding_drift_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Cosine Distance Type Embedding Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT cosine_dist_drift, \"timestamp\" FROM embedding_drift_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Drift Detection",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", total_drift_detected FROM embedding_drift_metrics LIMIT 50 "
    }
   ]
  }
 ]
}